version: "3"

services:
  app:
    container_name: challenge-app
    build: .
    command: yarn dev
    ports:
      - "3080:3000"
    volumes:
      - .:/usr/app
    expose:
      - "3080"

  mysql:
    container_name: challenge-mysql
    image: mysql:8.0.30
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./.data/db:/var/lib/mysql"
    # command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: challenge
      MYSQL_DATABASE: challenge
      TZ: America/Manaus
    expose:
      - "3310"
      
volumes:
  mysql:
    driver: local