version: "3"

services:
  mysql:
    container_name: challenge-mysql
    image: mysql:8.0.30
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./.data/db:/var/lib/mysql"
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      #define acessos de usuário root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      # Cria a base de dados
      MYSQL_DATABASE: challenge
    expose:
      - "3306"

  api:
    container_name: challenge-api
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /home/app/node_modules
    environment:
      DB_USER: root
      DB_NAME: challenge
      DB_PASS: 123456
      DB_HOST: mysql
      PORT: 3000
      TZ: "-04:00"
      JWT_SECRET: user_token
    expose:
      - "3000"
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql:
    driver: local
